# 6. 패키지 (Package)

- 특정 목적을 수행하는 모듈을 모아놓은(폴더 형태로) 집합체
- 모듈을 계층적인 구조로 관리하기 위해 사용
- 매우 복잡하고 다양한 기능이 수행되는 경우, 많은 모듈이 필요하며, 이를 패키지로 쉽게 다룰 수 있음

In [1]:
# Package1 폴더에 있는 modul1.py 파일, 모듈을 호출하여 사용
from package1 import modul1

In [2]:
modul1.fibo(10)

55

In [3]:
# 초기화 폴더 __init__.py
import package1

In [5]:
package1.pack_version()

package version : (VERSION)

## 6-1. 기타 파이썬 내장 함수 및 표준 라이브러리

- 라이브러리: 특정 프로그래밍 목적을 수행하기 위한 모듈 또는 패키지의 집합체
- 표준 라이브러리: 파이썬 내에 직접 사용이 가능한 함수 또는 모듈/ 패키지
      - 간단한 과학/ 통계 연산, 데이터처리, 파일불러오기 등
      - 약 50여가지의 내장 함수가 존재

- 외장 라이브러리의 경우 추가적으로 다운로드 받아서 사용

In [6]:
# 절대값 반환
abs(-100)

100

In [8]:
# 특정 데이터 값을 정렬하는 함수 (리스트, 튜플, 셋 사용 가능)
t1 =(10,2000,30,20,3,1,5)
type(t1)

tuple

In [9]:
sorted(t1) # 숫자의 정렬 결과가 리스트 형태로 출력

[1, 3, 5, 10, 20, 30, 2000]

In [10]:
sorted(t1, reverse=True) # 내림차순으로 정렬

[2000, 30, 20, 10, 5, 3, 1]

In [12]:
# 특정 개체가 가진 변수나 함수, 기능들을 확인하는 함수
dir( [10,20] ) # 리스트 자료구조 내에서 사용할 수 있는 함수들을 모두 확인 가능

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [14]:
# 자료구조 내 값을 순서와 값으로 나누어 연산
index_list = [] 
value_list = []
for i, data in enumerate(['A','B','C','D']):
    index_list.append(i)
    value_list.append(data)

dict(zip(index_list, value_list))

{0: 'A', 1: 'B', 2: 'C', 3: 'D'}

In [15]:
index_list

[0, 1, 2, 3]

In [16]:
value_list

['A', 'B', 'C', 'D']

In [17]:
# 시간 관련 표준 라이브러리
# 현장에서 데이터분석에 중요한 타입 중 하나가 시간에 대한 데이터 타입
import datetime

In [20]:
start_time = datetime.datetime.today() # 현재 시스템 상 시간
end_time = datetime.datetime(2025,1,1) # 특정 원하는 날짜를 지정

In [21]:
start_time - end_time

datetime.timedelta(days=557, seconds=66625, microseconds=70628)

In [22]:
start_time.weekday() # 요일/ 0-월/ 1-화/ 2-수/ 3-목/ 4-금/ 5-토/ 6-일

6

In [23]:
import time

In [25]:
time.time()
# UTC (Universal time coordinated, 협정 세계 표준시)를 사용하여,
# 1970년 1월 1일 0시0분0초를 기준으로 현재까지 몇 초가 흘렀는지 계산

1783848731.6298792

In [26]:
time.localtime(time.time())

time.struct_time(tm_year=2026, tm_mon=7, tm_mday=12, tm_hour=18, tm_min=32, tm_sec=29, tm_wday=6, tm_yday=193, tm_isdst=0)

In [27]:
# 코드에 일정한 시간 간격을 두고 코드를 수행
t1 = time.time()
time.sleep(10) # sleep(): 특정 초만큼 해당 코드를 정지
t2 =  time.time()

In [28]:
t2-t1

10.000657320022583

In [29]:
# 난수 생성과 관련된 라이브러리
import random

In [31]:
random.random() # 0과 1 사이의 수에서 난수를 생성

0.4715737910930896

In [32]:
random.randint(1,100) # 특정 범위의 정수 내에서 난수를 생성

52

In [33]:
# 수학 관련 함수를 쓸 수 있는 라이브러리
import math

In [35]:
# 두 수의 최소공배수를 계산 (두 수의 공통 배수 중 가장 작은 수)
math.lcm(20,30)

60

In [36]:
# 최대 공약수
math.gcd(20,30)

10

In [37]:
# 팩토리얼
math.factorial(3)

6

## 6-3. 정규표현식

- 정규표현식(Regular Expression)은 문자열을 처리할 때 특정 패턴을 정의하는데 사용되는 문자열
- 문자열 패턴을 사용하여, 문자열 검색, 대체, 추출 작업 등을 수행
- 정규표현식은 특정 규칙을 가지고있어, 다양한 문자와 연산자를 조합하여 복잡한 문자 패턴을 표현
- 크롤링 또는 자연어처리에서 데이터의 특정 패턴을 찾거나 추출할 때 사용

**메타 문자 (Meta Characters)**
- 문자가 가진 원래의 의미가 아닌 특별한 용도로 사용되는 문자
- 정규표현식에서는 대괄호 [] 안에 포함된 문자들 중 하나와 매치를 뜻함

In [38]:
# . ^ $ +
import re

In [41]:
# 대괄호 []: 대괄호 내 포함된 문자들 중 하나와 매칭되는지 확인
pattern = r'[abc]'
# Row string -> r 문자열 내에 메타 문자가 포함되어 있다

In [42]:
text1 = 'apple is 사과'
re.findall(pattern, text1)

['a']

In [44]:
pattern = r'[a-z]' # [ ] 내 두 문자 사이에 - 기호를 사용하면, 두 문자 사이의 범위를 지정
re.findall(pattern, text1)
# findall(): 문자열 전체에서 패턴과 일치하는 모든 부분을 찾아 리스트로 변환

['a', 'p', 'p', 'l', 'e', 'i', 's']

In [46]:
pattern = r'[가-힣]' # 한글 유니코드의 자음 + 모음 조합 범위
text2 = "so you don't cry for me 세월 지나도 난 변하지 않아 ~"
re.findall(pattern, text2)

['세', '월', '지', '나', '도', '난', '변', '하', '지', '않', '아']

In [47]:
pattern = r'[가-힣]+' # 공백을 기준으로 문자의 패턴을 확인
re.findall(pattern, text2)

['세월', '지나도', '난', '변하지', '않아']

In [48]:
# ^ : 해당 문자열을 제외한 나머지 패턴을 확인
pattern = r'[^가-힣]+' 
re.findall(pattern, text2)

["so you don't cry for me ", ' ', ' ', ' ', ' ', ' ~']

In [49]:
pattern = r'[a-zA-Z]+' # 모든 알파벳 표현 단어를 추출
re.findall(pattern,text2)

['so', 'you', 'don', 't', 'cry', 'for', 'me']

In [50]:
pattern = r'\d+' # \d: 모든 숫자/ 
text3 = "1초라도 안보이면, 2이렇게 초조한데, 3삼초는 어떻게 기다려 이아아 2020"
re.findall(pattern,text3)

['1', '2', '3', '2020']

In [51]:
# 소괄호는 특정 패턴 앞이나 뒤의 값을 확인
pattern = r'(\d+)\원'
text4= '2000원짜리 아이스크림 4개 주세요. 500원 잔돈입니다.'
re.findall(pattern,text4)

['2000', '500']

In [53]:
# re.sub() : 패턴과 일치하는 모든 부분을 다른 문자로 대치
text5 = "그댄 나의 챔피언 너와 나의 챔피언 우리 함께 외치면 승리하리라 한국"
pattern = r"챔피언"
replace_pattern = '챔피온~'

re.sub(pattern, replace_pattern, text5)

'그댄 나의 챔피온~ 너와 나의 챔피온~ 우리 함께 외치면 승리하리라 한국'

In [54]:
# re.split(): 특정 패턴을 기준으로 문자를 분할
pattern = r'\W+'
re.split(pattern, text5)

['그댄', '나의', '챔피언', '너와', '나의', '챔피언', '우리', '함께', '외치면', '승리하리라', '한국']

# 7. 데이터 분석 라이브러리

- 라이브러리: 특정 프로그래밍의 목적을 달성하기 위한 함수들의 집합체
- 데이터 분석을 위한 라이브러리 종류
- Numpy (Numeric + Python): 연속형 자료에 대한 과학/ 통계/ 수학 연산 관련 함수들의 집합
- Pandas (Panel + Dataset): 정형데이터(text, csv, excel... SQ)를 처리/분석/ 통계/ 연산 함수들의 집합

- Matplotlib (Matlab + Plot + Library): 연속형 자료들의 그래프를 시각화하는 함수들의 집합
- Seaborn: 정형데이터의 통계적 연산 및 시각화
- Plotly: 정형데이터의 시각화 (동적 시각화)

- Scipy (sicence + Python) : 응용통계(가설 검정/ 회귀분석/ 시계열 분석) 함수들의 집합
- Scikit-Learn (Science + Python + Learning + Toolit): 정형데이터에서 기계학습(데이터 마이닝) 함수들의 집합
- Tensorflow (Tensor + flow): 비정형데이터 처리 + 신경망 알고리즘(딥러닝) 함수를 집합
- Keras: 신경망 알고리즘 함수들의 집합
- Pytorch: 비정형 데이터 처리/ 딥러닝/ ...
- Request: 웹으로부터 정보를 주고 받거나 추출할 때 사용
- bs4: 웹 기반(HTML) 형식의 자료를 분해하여 정보를 추출할 때 사용
- selenium: 프로그램이나 어플리케이션의 진단 및 자동화/ 크롤링 사용

In [58]:
# 라이브러리를 해당 스크립트로 호출
import pandas as pd
# import: 특정 라이브러리를 스크립트로 호출
#as: 해당 라이브러리 이름을 줄여 사용

In [63]:
# 데이터 불러오기 (read_csv: csv파일을 불러옴)
df1 = pd.read_csv('01_Data.csv') # 01_Data.csv 파일을 불러와 df1 변수로 선
# FileNotFoundError: 해당 파일이 존재하지 않음 > 파일명 확인/ 파일 위치 확인
# SyntaxError: 들여쓰기/ 띄어쓰기 오류 > 함수명 확인 ...

In [67]:
# 고객관리 CRM 데이터
# 데이터의 순서 Index
df1.index
# 함수에서 소괄호를 안쓰는 경우 -> 데이터의 구조를 확인하는 경우

RangeIndex(start=0, stop=51301, step=1)

In [68]:
# 데이터의 항목 column
df1.columns

Index(['Index', 'Member_ID', 'Sales_Type', 'Contract_Type', 'Channel',
       'Datetime', 'Term', 'Payment_Type', 'Product_Type', 'Amount_Month',
       'Customer_Type', 'Age', 'Address1', 'Address2', 'State',
       'Overdue_count', 'Overdue_Type', 'Gender', 'Credit_Rank', 'Bank'],
      dtype='object')

In [72]:
# 데이터 구조와 타입을 확인
df1.info()
# 결측값 (Missing Value): 데이터의 공백/ Null, None, NaN(Not a Numver)...
# Non-Null Count: 결측값이 아닌, 존재하는 데이터의 개수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          51301 non-null  int64
 1   Member_ID      51301 non-null  int64
 2   Sales_Type     51301 non-null  object
 3   Contract_Type  51301 non-null  object
 4   Channel        51301 non-null  object
 5   Datetime       51301 non-null  object
 6   Term           51301 non-null  int64
 7   Payment_Type   51301 non-null  object
 8   Product_Type   51301 non-null  object
 9   Amount_Month   51301 non-null  int64
 10  Customer_Type  51299 non-null  object
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object
 13  Address2       51299 non-null  object
 14  State          51301 non-null  object
 15  Overdue_count  51301 non-null  int64
 16  Overdue_Type   51301 non-null  object
 17  Gender         51301 non-null  object
 18  Credit_Rank    42520 non-null  float64
 19  Bank           48542 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.8+ MB

# 데이터 전처리

- 데이터 핸들링 기법
- 
      - 데이터 추출 (행단위/ 열단위)
      - 데이터 정렬
      - 데이터 필터
      - 데이터 요약 (Pivot)
      - 날짜 데이터 처리/ 파생변수:  기존에 있는 데이터 항목을 이용해 새로운 항목을 만드는 것
      - 데이터 재구조화/ 병합

In [73]:
# 데이터 추출 (행단위)
df1.head() # head(): 상위 n개의 데이터를 추출할 때 사용 (공백 > 5개)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합

In [74]:
df1.tail() # tail(): 하위 n개의 데이터를 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [76]:
# 특정 범위의 데이터를 확인할 때
# iloc[n:m]: n번째부터 m번 이전까지 데이터를 추출
df1.iloc[50:100]

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
50,51,66758548,렌탈,일반계약,영업방판,2019-03-31,60,CMS,DES-1,96900,개인,57.0,서울특별시,서울특별시,계약확정,0,없음,남자,4.0,국민은행
51,52,66758162,렌탈,패키지계약,홈쇼핑/방송,2019-10-03,60,카드이체,DES-1,98400,개인,50.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,국민카드
52,53,66758162,렌탈,패키지계약,홈쇼핑/방송,2019-05-04,60,카드이체,DES-2,80400,개인,50.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,국민카드
53,54,66590304,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-2,90900,개인,43.0,서울특별시,서울특별시,계약확정,0,없음,남자,4.0,신한은행
54,55,66670488,렌탈,프로모션계약,영업방판,2019-04-03,60,CMS,DES-1,96900,개인,34.0,서울특별시,서울특별시,계약확정,0,없음,여자,4.0,우리은행
55,56,25856039,렌탈,교체계약,영업방판,2019-05-01,60,CMS,DES-1,96900,사업자,NaN,경상도,부산광역시,계약확정,0,없음,여자,NaN,농협중앙회
56,57,25869517,렌탈,프로모션계약,영업방판,2019-07-22,60,가상계좌,DES-1,96900,사업자,NaN,경상도,부산광역시,계약확정,0,없음,여자,NaN,NaN
57,58,66757967,렌탈,프로모션계약,영업방판,2019-08-21,60,카드이체,DES-1,105900,개인,37.0,경상도,경상도,계약확정,0,없음,여자,5.0,롯데카드
58,59,66260467,렌탈,교체계약,영업방판,2019-02-16,60,CMS,DES-1,96900,개인,42.0,경상도,경상도,계약확정,0,없음,여자,1.0,우리은행
59,60,66758899,렌탈,패키지계약,전문매장H,2019-07-30,60,CMS,DES-1,81900,개인,67.0,경상도,경상도,계약확정,0,없음,남자,2.0,대구은행
60,61,66758899,렌탈,패키지계약,전문매장H,2020-01-22,60,CMS,DES-2,81900,개인,67.0,경상도,경상도,계약확정,0,없음,남자,2.0,대구은행
61,62,66758851,렌탈,일반계약,영업방판,2019-01-04,60,CMS,DES-R4,126900,개인,27.0,경기도,인천광역시,계약확정,12,있음,남자,5.0,농협중앙회
62,63,66757441,렌탈,프로모션계약,영업방판,2019-01-31,60,CMS,DES-3A,90900,개인,55.0,경기도,인천광역시,계약확정,0,없음,남자,7.0,농협회원조합
63,64,66758704,렌탈,프로모션계약,대형마트H,2019-03-09,60,CMS,DES-1,96900,개인,38.0,경기도,인천광역시,계약확정,0,없음,남자,6.0,우리은행
64,65,66420963,멤버십,멤버십3유형,재계약,2019-04-29,12,CMS,DES-1,66900,개인,61.0,경기도,인천광역시,계약확정,0,없음,여자,NaN,국민은행
65,66,66758888,렌탈,프로모션계약,대형마트E,2019-06-30,60,CMS,DES-1,105900,개인,34.0,경기도,경기도,계약확정,0,없음,여자,NaN,우리은행
66,67,66754426,렌탈,프로모션계약,홈쇼핑/방송,2019-10-02,60,CMS,DES-1,105900,개인,55.0,경기도,경기도,계약확정,0,없음,여자,2.0,국민은행
67,68,66758803,렌탈,프로모션계약,대형마트E,2020-03-23,60,CMS,DES-1,105900,개인,41.0,경기도,경기도,계약확정,0,없음,여자,9.0,국민은행
68,69,66758803,렌탈,프로모션계약,대형마트E,2020-06-29,36,CMS,DES-2,96900,개인,41.0,경기도,경기도,계약확정,0,없음,여자,9.0,국민은행
69,70,66755965,렌탈,일반계약,영업방판,2020-07-29,60,CMS,DES-1,96900,개인,41.0,경기도,경기도,계약확정,0,없음,여자,9.0,국민은행
70,71,66316787,렌탈,프로모션계약,홈쇼핑/방송,2019-01-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,남자,2.0,국민은행
71,72,66758653,렌탈,패키지계약,홈쇼핑/방송,2019-02-25,60,CMS,DES-1,81900,개인,69.0,경기도,경기도,계약확정,0,없음,여자,3.0,하나은행
72,73,66758653,렌탈,패키지계약,홈쇼핑/방송,2019-05-08,60,CMS,DES-2,81900,개인,69.0,경기도,경기도,계약확정,0,없음,여자,3.0,하나은행
73,74,66388766,렌탈,교체계약,영업방판,2019-07-13,60,카드이체,DES-1,96900,개인,36.0,경기도,경기도,계약확정,0,없음,남자,NaN,롯데카드
74,75,66750147,렌탈,일반계약,홈쇼핑/인터넷,2019-05-29,60,CMS,DES-1,96900,개인,56.0,경기도,경기도,계약확정,0,없음,여자,1.0,신한은행
75,76,66426523,렌탈,프로모션계약,영업방판,2019-01-01,60,카드이체,DES-3A,90900,개인,51.0,경기도,경기도,계약확정,0,없음,남자,6.0,롯데카드
76,77,66758873,렌탈,패키지계약,홈쇼핑/방송,2019-05-27,60,CMS,DES-1,81900,개인,68.0,경기도,경기도,계약확정,0,없음,남자,3.0,우리은행
77,78,66758873,렌탈,패키지계약,홈쇼핑/방송,2019-05-27,60,CMS,DES-2,81900,개인,68.0,경기도,경기도,계약확정,0,없음,남자,3.0,우리은행
78,79,25742711,렌탈,프로모션계약,영업방판,2019-06-11,60,CMS,DES-1,124200,사업자,60.0,경기도,경기도,계약확정,0,없음,여자,NaN,신한은행
79,80,66422805,렌탈,교체계약,영업방판,2019-06-30,60,CMS,DES-1,102900,개인,56.0,경기도,경기도,계약확정,0,없음,여자,2.0,신한은행
80,81,66543103,렌탈,교체계약,영업방판,2019-09-12,60,CMS,DES-1,102900,개인,43.0,경기도,경기도,계약확정,0,없음,남자,1.0,국민은행
81,82,66144881,렌탈,교체계약,영업방판,2019-01-03,60,CMS,DES-1,96900,개인,51.0,경기도,경기도,계약확정,0,없음,남자,3.0,농협중앙회
82,83,66747865,렌탈,프로모션계약,홈쇼핑/방송,2019-01-03,60,카드이체,DES-1,105900,개인,56.0,경기도,경기도,계약확정,1,있음,남자,1.0,국민카드
83,84,25742708,렌탈,프로모션계약,영업방판,2019-01-15,60,CMS,DES-1,124200,사업자,56.0,경기도,경기도,계약확정,0,없음,여자,NaN,우리은행
84,85,25742708,렌탈,일반계약,영업방판,2019-08-21,60,CMS,DES-3A,102900,사업자,56.0,경기도,경기도,계약확정,0,없음,여자,NaN,우리은행
85,86,25742710,렌탈,프로모션계약,영업방판,2019-09-10,60,CMS,DES-1,124200,사업자,56.0,경기도,경기도,계약확정,0,없음,여자,NaN,우리은행
86,87,25742710,렌탈,일반계약,영업방판,2019-12-25,60,CMS,DES-3A,102900,사업자,56.0,경기도,경기도,계약확정,0,없음,여자,NaN,우리은행
87,88,66758514,렌탈,일반계약,영업방판,2020-01-15,60,카드이체,DES-1,124200,개인,60.0,경기도,경기도,계약확정,0,없음,여자,5.0,롯데카드
88,89,66758843,렌탈,프로모션계약,전문매장Z,2020-05-27,60,CMS,DES-1,96900,개인,73.0,경기도,경기도,계약확정,0,없음,남자,4.0,농협회원조합
89,90,66758546,렌탈,프로모션계약,홈쇼핑/방송,2020-08-06,60,카드이체,DES-1,96900,개인,77.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,신한카드
90,91,66369912,렌탈,프로모션계약,영업방판,2019-01-05,60,CMS,DES-1,111900,개인,35.0,서울특별시,서울특별시,계약확정,0,없음,여자,4.0,우리은행
91,92,66758588,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-1,105900,개인,83.0,서울특별시,서울특별시,계약확정,0,없음,남자,3.0,농협회원조합
92,93,66643114,렌탈,프로모션계약,영업방판,2019-09-10,60,CMS,DES-2,90900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,7.0,농협중앙회
93,94,66879582,렌탈,프로모션계약,대형마트H,2020-06-18,60,CMS,DES-1,96900,개인,52.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,신한은행
94,95,66758611,렌탈,일반계약,홈쇼핑/방송,2019-01-20,60,카드이체,DES-1,96900,개인,60.0,서울특별시,서울특별시,계약확정,0,없음,남자,1.0,신한카드
95,96,25751808,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,사업자,NaN,경기도,경기도,계약확정,15,있음,여자,NaN,기업은행
96,97,66758771,렌탈,일반계약,영업방판,2019-10-23,60,CMS,DES-1,96900,개인,49.0,경기도,경기도,계약확정,0,없음,남자,1.0,농협회원조합
97,98,66677887,렌탈,프로모션계약,영업방판,2019-04-14,60,카드이체,DES-1,96900,개인,52.0,경기도,경기도,계약확정,0,없음,여자,1.0,롯데카드
98,99,66758748,렌탈,프로모션계약,전문매장H,2019-04-14,60,카드이체,DES-1,96900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,3.0,삼성카드
99,100,66423756,멤버십,멤버십3유형,재계약,2019-01-01,12,CMS,DES-1,75900,개인,32.0,전라도,광주광역시,계약확정,0,없음,남자,NaN,하나은행

In [81]:
# 상위 150개의 데이터를 뽑아서 result.csv 파일로 저장
# to_csv(): csv 파일 형식으로 데이터를 저장
df1.head(150).to_csv('result.csv', encoding='cp949')
# df1 데이터에서 먼저 150개의 데이터를 추출한 뒤, result.csv파일로 저장된 순

In [80]:
df1.head(150).to_excel('result.xlsx')

- csv: Comma Separated Values 콤마로 구분된 데이터를 정리한 파일
   - 정형데이터의 구조를 가지고 있지않음
- excel:
   - 정형데이터의 구조(index~ column~ value)를 가진상태에서 파일을 저장

In [83]:
# 열단위 추출
df1["Amount_Month"] # 하나의 열 데이터를 추출
# Series 구조: Index- value (순서- 값/ 순열)

0         96900
1        102900
2         96900
3         66900
4         66900
          ...
51296     96900
51297     96900
51298    120900
51299     96900
51300     96900
Name: Amount_Month, Length: 51301, dtype: int64

In [84]:
df1['Amount_Month'].mean() # 하나의 열의 평균값을 계산

np.float64(93994.97428900021)

In [85]:
# Data Frame 구조: Index - Column - Value
# Series가 여러 줄 모이면 하나의 data frame이 구성된다
# 여러 열을 추출할 때
df1[['Amount_Month','Channel','Sales_Type']]

       Amount_Month Channel Sales_Type
0             96900    영업방판         렌탈
1            102900    영업방판         렌탈
2             96900  홈쇼핑/방송         렌탈
3             66900     재계약        멤버십
4             66900     재계약        멤버십
...             ...     ...        ...
51296         96900   대형마트A         렌탈
51297         96900   대형마트A         렌탈
51298        120900    영업방판         렌탈
51299         96900  홈쇼핑/방송         렌탈
51300         96900  홈쇼핑/방송         렌탈

[51301 rows x 3 columns]

In [86]:
df1[['Amount_Month','Channel']].head(10)

   Amount_Month Channel
0         96900    영업방판
1        102900    영업방판
2         96900  홈쇼핑/방송
3         66900     재계약
4         66900     재계약
5         90900    영업방판
6         98400  홈쇼핑/방송
7         80400  홈쇼핑/방송
8        102900    영업방판
9        105900    영업방판

In [87]:
# 데이터 정렬 (sort_values(): 특정 데이터에 대한 정렬)
df1.sort_values(by='Amount_Month') # 오름차순 정렬

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
41962,41964,66791993,멤버십,멤버십2유형,전문매장H,2019-07-15,36,무통장,DES-1,54603,개인,NaN,경상도,대구광역시,계약확정,0,없음,여자,NaN,NaN
49855,49857,66797877,멤버십,멤버십2유형,전문매장H,2019-02-23,36,무통장,DES-1,54603,개인,NaN,경상도,경상도,계약확정,0,없음,여자,NaN,NaN
39280,39282,66788217,멤버십,멤버십2유형,전문매장H,2019-06-25,36,무통장,DES-1,54603,개인,NaN,충청도,충청도,계약확정,0,없음,여자,NaN,NaN
39095,39097,66788838,멤버십,멤버십2유형,전문매장H,2019-03-26,36,무통장,DES-1,54603,개인,NaN,충청도,대전광역시,계약확정,0,없음,여자,NaN,NaN
43978,43980,66793345,멤버십,멤버십2유형,전문매장H,2019-08-24,36,무통장,DES-1,54603,개인,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35085,35087,25867372,렌탈,프로모션계약,영업방판,2019-02-07,39,가상계좌,MMC,215700,사업자,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
38497,38499,25734005,렌탈,프로모션계약,영업방판,2019-06-05,39,CMS,MMC,215700,사업자,58.0,전라도,전라도,계약확정,0,없음,남자,1.0,농협중앙회
35084,35086,25867372,렌탈,프로모션계약,영업방판,2019-05-01,39,가상계좌,MMC,215700,사업자,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
19774,19776,25740247,렌탈,프로모션계약,전단홍보,2020-01-17,39,가상계좌,MMC,215700,사업자,NaN,경상도,경상도,계약확정,0,없음,여자,NaN,NaN
19773,19775,25740247,렌탈,프로모션계약,전단홍보,2019-11-14,39,가상계좌,MMC,215700,사업자,NaN,경상도,경상도,계약확정,0,없음,여자,NaN,NaN

In [88]:
#내림차순 정렬
df1.sort_values(by='Amount_Month', ascending=False)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
38497,38499,25734005,렌탈,프로모션계약,영업방판,2019-06-05,39,CMS,MMC,215700,사업자,58.0,전라도,전라도,계약확정,0,없음,남자,1.0,농협중앙회
5399,5400,25742182,렌탈,프로모션계약,영업방판,2019-05-18,39,CMS,MMC,215700,사업자,NaN,경기도,경기도,계약확정,1,있음,여자,NaN,신한은행
44840,44842,25732681,렌탈,프로모션계약,영업방판,2020-06-01,39,CMS,MMC,215700,사업자,51.0,경상도,경상도,계약확정,2,있음,여자,NaN,우체국
37522,37524,25733781,렌탈,프로모션계약,영업방판,2020-07-02,39,CMS,MMC,215700,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,기업은행
35085,35087,25867372,렌탈,프로모션계약,영업방판,2019-02-07,39,가상계좌,MMC,215700,사업자,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47467,47469,66796319,멤버십,멤버십2유형,전문매장H,2019-07-28,36,무통장,DES-1,54603,개인,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN
33844,33846,66783744,멤버십,멤버십2유형,전문매장H,2019-03-22,36,무통장,DES-1,54603,개인,NaN,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,NaN
46007,46009,66793313,멤버십,멤버십2유형,전문매장H,2020-07-04,36,무통장,DES-1,54603,개인,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN
46016,46018,66794814,멤버십,멤버십2유형,전문매장H,2019-09-15,36,무통장,DES-1,54603,개인,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN
48996,48998,66795599,멤버십,멤버십2유형,전문매장H,2019-09-15,36,무통장,DES-1,54603,개인,NaN,전라도,광주광역시,계약확정,0,없음,여자,NaN,NaN

In [89]:
# 월렌탈비용('Amount_Month')이 높으면서, 연령(Age)이 높은 순서대로 정렬
df1.sort_values(by=['Amount_Month','Age'],ascending=False)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
38497,38499,25734005,렌탈,프로모션계약,영업방판,2019-06-05,39,CMS,MMC,215700,사업자,58.0,전라도,전라도,계약확정,0,없음,남자,1.0,농협중앙회
44838,44840,25732681,렌탈,프로모션계약,영업방판,2020-04-12,39,CMS,MMC,215700,사업자,51.0,경상도,경상도,계약확정,2,있음,여자,NaN,우체국
44839,44841,25732681,렌탈,프로모션계약,영업방판,2020-04-18,39,CMS,MMC,215700,사업자,51.0,경상도,경상도,계약확정,2,있음,여자,NaN,우체국
44840,44842,25732681,렌탈,프로모션계약,영업방판,2020-06-01,39,CMS,MMC,215700,사업자,51.0,경상도,경상도,계약확정,2,있음,여자,NaN,우체국
5399,5400,25742182,렌탈,프로모션계약,영업방판,2019-05-18,39,CMS,MMC,215700,사업자,NaN,경기도,경기도,계약확정,1,있음,여자,NaN,신한은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51210,51212,66799109,멤버십,멤버십2유형,전문매장H,2019-09-04,36,무통장,DES-1,54603,개인,NaN,경상도,부산광역시,계약확정,0,없음,여자,NaN,NaN
51277,51279,66799700,멤버십,멤버십2유형,전문매장H,2019-02-24,36,무통장,DES-1,54603,개인,NaN,경기도,인천광역시,계약확정,0,없음,여자,NaN,NaN
51280,51282,66799156,멤버십,멤버십2유형,전문매장H,2019-03-10,36,무통장,DES-1,54603,개인,NaN,전라도,광주광역시,계약확정,0,없음,여자,NaN,NaN
51284,51286,66799094,멤버십,멤버십2유형,전문매장H,2019-02-24,36,무통장,DES-1,54603,개인,NaN,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,NaN
51290,51292,66798812,멤버십,멤버십2유형,전문매장H,2020-01-28,36,무통장,DES-1,54603,개인,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN

In [90]:
df1.sort_values(by=['Amount_Month','Age'],ascending=[True,False])

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
33107,33109,66783626,멤버십,멤버십2유형,전문매장H,2019-12-19,36,무통장,DES-1,54603,개인,NaN,경상도,경상도,계약확정,0,없음,여자,NaN,NaN
33803,33805,66783630,멤버십,멤버십2유형,전문매장H,2020-07-28,36,무통장,DES-1,54603,개인,NaN,경기도,인천광역시,계약확정,0,없음,여자,NaN,NaN
33844,33846,66783744,멤버십,멤버십2유형,전문매장H,2019-03-22,36,무통장,DES-1,54603,개인,NaN,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,NaN
34129,34131,66783985,멤버십,멤버십2유형,전문매장H,2020-01-22,36,무통장,DES-1,54603,개인,NaN,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,NaN
34311,34313,66783750,멤버십,멤버십2유형,전문매장H,2019-02-21,36,무통장,DES-1,54603,개인,NaN,경상도,대구광역시,계약확정,0,없음,여자,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35084,35086,25867372,렌탈,프로모션계약,영업방판,2019-05-01,39,가상계좌,MMC,215700,사업자,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
35085,35087,25867372,렌탈,프로모션계약,영업방판,2019-02-07,39,가상계좌,MMC,215700,사업자,NaN,강원도,강원도,계약확정,0,없음,여자,NaN,NaN
37522,37524,25733781,렌탈,프로모션계약,영업방판,2020-07-02,39,CMS,MMC,215700,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,기업은행
49896,49898,25731710,렌탈,프로모션계약,영업방판,2019-09-30,39,가상계좌,MMC,215700,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN
49897,49899,25731710,렌탈,프로모션계약,영업방판,2019-12-06,39,가상계좌,MMC,215700,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,NaN

In [91]:
# 월렌탈비용('Amount_Month')이 높고, 연체건수('Overdue_count')는 낮은 상위 50명의
# 고객 계약 명단을 추출해서 result2.xlsx
df1.sort_values(by=['Amount_Month','Overdue_count'],
                ascending=[False,True]).head(50).to_excel('result2.xlsx')

In [95]:
# 데이터 추출 (Filter)/ loc[(조건식)] : 특정 조건(True)에 해당하는 데이터를 추출
# 층별화: 범주형 데이터 항목의 특성에 따라 다른 데이터의 통계적 특성이 달라질 수 있다.

# 월렌탈비용이 10만원 이상인 고객들 
cond1 = (df1['Amount_Month'] >= 100000) # 월렌탈비용이 10만원 이상인 조건
df1.loc[cond1] # 해당 조건에 대한 데이터를 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
8,9,66758007,렌탈,일반계약,영업방판,2019-06-30,60,카드이체,DES-3A,102900,개인,62.0,경상도,경상도,계약확정,0,없음,여자,2.0,롯데카드
9,10,66756702,렌탈,프로모션계약,영업방판,2019-06-30,60,CMS,DES-1,105900,개인,51.0,경상도,경상도,계약확정,0,없음,여자,1.0,신한은행
19,20,66755490,렌탈,프로모션계약,영업방판,2020-01-17,60,카드이체,DES-1,105900,개인,58.0,경상도,부산광역시,계약확정,0,없음,여자,1.0,롯데카드
21,22,66758336,렌탈,프로모션계약,전문매장Z,2020-04-25,60,CMS,DES-1,111900,개인,72.0,경상도,부산광역시,계약확정,0,없음,남자,9.0,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51286,51288,66799302,렌탈,프로모션계약,영업방판,2019-05-21,60,카드이체,DES-1,105900,개인,39.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51287,51289,66444051,렌탈,교체계약,대형마트A,2019-09-29,60,CMS,DES-1,102900,개인,90.0,서울특별시,서울특별시,계약확정,0,없음,남자,NaN,신한은행
51288,51290,66799492,렌탈,프로모션계약,영업방판,2019-02-24,60,카드이체,DES-1,105900,개인,52.0,경기도,경기도,계약확정,0,없음,남자,NaN,삼성카드
51291,51293,25731743,렌탈,일반계약,영업방판,2020-02-12,60,CMS,DES-3A,102900,사업자,NaN,경기도,경기도,계약확정,10,있음,여자,NaN,농협중앙회
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드

In [98]:
# 월렌탈비용이 10만원 이상이면서 
# 연체건수가 5만원 이하인 고객명단을 추출
cond1 = (df1['Amount_Month']>=100000)
cond2 = (df1['Overdue_count'] <=5)
df1.loc[cond1&cond2] # 두 조건을 모두 만족하는 경우 (And &)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
8,9,66758007,렌탈,일반계약,영업방판,2019-06-30,60,카드이체,DES-3A,102900,개인,62.0,경상도,경상도,계약확정,0,없음,여자,2.0,롯데카드
9,10,66756702,렌탈,프로모션계약,영업방판,2019-06-30,60,CMS,DES-1,105900,개인,51.0,경상도,경상도,계약확정,0,없음,여자,1.0,신한은행
19,20,66755490,렌탈,프로모션계약,영업방판,2020-01-17,60,카드이체,DES-1,105900,개인,58.0,경상도,부산광역시,계약확정,0,없음,여자,1.0,롯데카드
21,22,66758336,렌탈,프로모션계약,전문매장Z,2020-04-25,60,CMS,DES-1,111900,개인,72.0,경상도,부산광역시,계약확정,0,없음,남자,9.0,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51279,51281,66798237,렌탈,패키지계약,직영계열사A,2019-03-09,60,CMS,DES-3A,101400,개인,NaN,경기도,인천광역시,계약확정,0,없음,여자,4.0,국민은행
51286,51288,66799302,렌탈,프로모션계약,영업방판,2019-05-21,60,카드이체,DES-1,105900,개인,39.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51287,51289,66444051,렌탈,교체계약,대형마트A,2019-09-29,60,CMS,DES-1,102900,개인,90.0,서울특별시,서울특별시,계약확정,0,없음,남자,NaN,신한은행
51288,51290,66799492,렌탈,프로모션계약,영업방판,2019-02-24,60,카드이체,DES-1,105900,개인,52.0,경기도,경기도,계약확정,0,없음,남자,NaN,삼성카드
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드

In [ ]:
df1.loc[cond1|cond2] # 두 조건 중 하나의 조건만 만족해도 데이터를 불러옴 (OR |)

df1.loc[(df1['Amount_Month']>=100000)&(df1['Overdue_count'] <=5)]

In [100]:
# 판매유형(Sales_Type)이 '렌탈'에 해당하는 데이터만 추출
cond1 = (df1['Sales_Type']=='렌탈')
df1.loc[cond1]

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
5,6,66165241,렌탈,프로모션계약,영업방판,2019-07-29,60,CMS,DES-3A,90900,개인,53.0,경상도,경상도,계약확정,0,없음,여자,5.0,농협중앙회
6,7,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-30,60,카드이체,DES-1,98400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [104]:
# 유입경로(channel)이 '영업방판' '홈쇼핑/방송' 대형마트A
# 여러 항목에 대해 데이터 추출
cond1 = (df1['Channel'].isin(['영업방판','홈쇼핑/방송','대형마트A']))
df1.loc[cond1]

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
5,6,66165241,렌탈,프로모션계약,영업방판,2019-07-29,60,CMS,DES-3A,90900,개인,53.0,경상도,경상도,계약확정,0,없음,여자,5.0,농협중앙회
6,7,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-30,60,카드이체,DES-1,98400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [105]:
# 결제은행이 현대카드에 해당하는 계약 명단 중
# 월렌탈비용이 1500000원 이상만 상위 50명의 계약명단을 추출하여
#result3.xlsx 에 저장
cond1 = (df1['Bank']=='현대카드')
cond2 =  (df1['Amount_Month']>=150000)
df1.loc[cond1&cond2].head(50).to_excel('result3.xlsx')

In [107]:
# 데이터 요약 (Pivot)/ pivot_table()
# 판매 유형별로 월렌탈비용의 평균을 계산

df1.pivot_table(index='Sales_Type',values='Amount_Month', aggfunc='mean')

# index= :구분하고자 하는 값
# values= : 계산하고자 하는 값
# aggfunc= : 계산하려는 통계량

            Amount_Month
Sales_Type
렌탈          97199.625024
멤버십         63077.211706

In [109]:
# 함수 내 인자 및 함수 설명
help(pd.pivot_table)

Help on function pivot_table in module pandas.core.reshape.pivot:

pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Hashable' = 'All',
    observed: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool' = True
) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.

    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.

    Parameters
    ----------
    data : DataFrame
    values : list-like or scalar, optional
        Column or columns to aggregate.
    index : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table index. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table column. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the same manner as column values.
    aggfunc : function, list of functions, dict, default "mean"
        If a list of functions is passed, the resulting pivot table will have
        hierarchical columns whose top level are the function names
        (inferred from the function objects themselves).
        If a dict is passed, the key is column to aggregate and the value is
        function or list of functions. If ``margin=True``, aggfunc will be
        used to calculate the partial aggregates.
    fill_value : scalar, default None
        Value to replace missing values with (in the resulting pivot table,
        after aggregation).
    margins : bool, default False
        If ``margins=True``, special ``All`` columns and rows
        will be added with partial group aggregates across the categories
        on the rows and columns.
    dropna : bool, default True
        Do not include columns whose entries are all NaN. If True,
        rows with a NaN value in any column will be omitted before
        computing margins.
    margins_name : str, default 'All'
        Name of the row / column that will contain the totals
        when margins is True.
    observed : bool, default False
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. deprecated:: 2.2.0

            The default value of ``False`` is deprecated and will change to
            ``True`` in a future version of pandas.

    sort : bool, default True
        Specifies if the result should be sorted.

        .. versionadded:: 1.3.0

    Returns
    -------
    DataFrame
        An Excel style pivot table.

    See Also
    --------
    DataFrame.pivot : Pivot without aggregation that can handle
        non-numeric data.
    DataFrame.melt: Unpivot a DataFrame from wide to long format,
        optionally leaving identifiers set.
    wide_to_long : Wide panel to long format. Less flexible but more
        user-friendly than melt.

    Notes
    -----
    Reference :ref:`the user guide <reshaping.pivot>` for more examples.

    Examples
    --------
    >>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
    ...                          "bar", "bar", "bar", "bar"],
    ...                    "B": ["one", "one", "one", "two", "two",
    ...                          "one", "one", "two", "two"],
    ...                    "C": ["small", "large", "large", "small",
    ...                          "small", "large", "small", "small",
    ...                          "large"],
    ...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    ...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
    >>> df
         A    B      C  D  E
    0  foo  one  small  1  2
    1  foo  one  large  2  4
    2  foo  one  large  2  5
    3  foo  two  small  3  5
    4  foo  two  small  3  6
    5  bar  one  large  4  6
    6  bar  one  small  5  8
    7  bar  two  small  6  9
    8  bar  two  large  7  9

    This first example aggregates values by taking the sum.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                        columns=['C'], aggfunc="sum")
    >>> table
    C        large  small
    A   B
    bar one    4.0    5.0
        two    7.0    6.0
    foo one    4.0    1.0
        two    NaN    6.0

    We can also fill missing values using the `fill_value` parameter.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                        columns=['C'], aggfunc="sum", fill_value=0)
    >>> table
    C        large  small
    A   B
    bar one      4      5
        two      7      6
    foo one      4      1
        two      0      6

    The next example aggregates by taking the mean across multiple columns.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                        aggfunc={'D': "mean", 'E': "mean"})
    >>> table
                    D         E
    A   C
    bar large  5.500000  7.500000
        small  5.500000  8.500000
    foo large  2.000000  4.500000
        small  2.333333  4.333333

    We can also calculate multiple types of aggregations for any given
    value column.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                        aggfunc={'D': "mean",
    ...                                 'E': ["min", "max", "mean"]})
    >>> table
                      D   E
                   mean max      mean  min
    A   C
    bar large  5.500000   9  7.500000    6
        small  5.500000   9  8.500000    8
    foo large  2.000000   5  4.500000    4
        small  2.333333   6  4.333333    2